### ISSUE TITLE
how

### ISSUE THREAD

**Issue by mohghezal** [wrenchonline/glint#9]
root@kali-desktop:/home/kali/glint-main# ./glint --cert server.pem --key server.key http://testphp.vulnweb.com/
[16:23:43][inf][main.CmdHandler]Enter command mode...
[16:23:43][inf][main.(*Task).dostartTasks]config.EnableCrawler: true
panic: reflect: call of reflect.Value.Int on string Value

goroutine 1 [running]:
reflect.Value.Int(...)
        /usr/local/go/src/reflect/value.go:1459
main.(*Task).dostartTasks(0xc0002dc000, {0x0, 0x1, 0x0, {0x0, 0x0}, {0x0, 0x0}})
        /home/kali/glint-main/glint.go:652 +0x1a28
main.CmdHandler(0xc000091ec0, 0xc0002dc000, {0x0, 0x1, 0x0, {0x0, 0x0}, {0x0, 0x0}})
        /home/kali/glint-main/glint.go:973 +0x350
main.run(0xc000091ec0)
        /home/kali/glint-main/glint.go:266 +0x237
github.com/urfave/cli/v2.(*App).RunContext(0xc0000e4700, {0x10ce3d0?, 0xc000042120}, {0xc0000401e0, 0x6, 0x6})
        /root/go/pkg/mod/github.com/urfave/cli/v2@v2.16.3/app.go:391 +0xf68
github.com/urfave/cli/v2.(*App).Run(...)
        /root/go/pkg/mod/github.com/urfave/cli/v2@v2.16.3/app.go:252
main.main()
        /home/kali/glint-main/glint.go:226 +0x729

**Comment by wrenchonline** [comment]
> 

hello,This program must configure itop_task.json and xss.yaml in the current running environment.

``` golang
const (
	DefaultConfigPath string = "itop_task.json"
	DefaultSocket     string = ""
	DefaultConfigType string = "json"
	ConfirmSocket     bool   = true
	UnconfirmSocket   bool   = false
)
```
I don't seem to be prepared enough for the configuration, I will improve it soon.Please pull the latest RP.
